# Generated by Django 4.2 on 2023-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(blank=True, max_length=25, null=True)),
                ('P_image', models.ImageField(upload_to='cart_image')),
                ('Price', models.FloatField(blank=True, max_length=10, null=True)),
                ('Total_price', models.FloatField(blank=True, max_length=10, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
