# Generated by Django 3.2.10 on 2023-05-21 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrontendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='P_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_image'),
        ),
    ]
