# Generated by Django 3.2.10 on 2023-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0004_contactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
