# Generated by Django 3.2.10 on 2023-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0005_auto_20230523_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
