# Generated by Django 3.2.10 on 2023-06-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrontendApp', '0006_auto_20230523_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(max_length=100)),
                ('Pin_Code', models.IntegerField()),
                ('Product_name', models.CharField(max_length=100)),
                ('Total_price', models.IntegerField()),
                ('User_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
