# Generated by Django 3.2.10 on 2023-06-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0007_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
