# Generated by Django 4.2 on 2023-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_image', models.ImageField(upload_to='c_image')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
