# Generated by Django 4.2 on 2023-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=25, null=True)),
                ('Category', models.CharField(blank=True, max_length=15, null=True)),
                ('p_image', models.ImageField(upload_to='p_image')),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
