# Generated by Django 4.2 on 2023-05-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Product',
            new_name='P_name',
        ),
    ]
