# Generated by Django 4.2 on 2023-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_product_productdb_p_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouserDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='cover_image')),
            ],
        ),
    ]
