# Generated by Django 4.2 on 2023-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_carouserdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouserdb',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
