# Generated by Django 3.2.10 on 2023-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_carouserdb_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
